version: '3.9'

services:
  web:
    build: ./app
    ports:
      - "${WEB_PORT:-8080}:8080"
    environment:
      - LOG_PATH=/data/logs.json
      - RULES_FILE=/data/rules.json
      - BLOCKLIST_BACKEND=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./data:/data
    depends_on:
      - redis

  waf:
    build: ./waf
    ports:
      - "${WAF_PORT:-8000}:8000"
    environment:
      - LOG_PATH=/data/logs.json
      - RULES_FILE=/data/rules.json
      - BLOCKLIST_BACKEND=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./waf/logs.json:/app/logs.json
      - ./data:/data
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
